### ISSUE TITLE
Remove eth support?

### ISSUE THREAD

**Issue by martinheidegger** [dnslink-std/js#1]
Following up on our conversation in https://github.com/ipfs/community/discussions/560: Should `.eth` support be removed from this implementation?

**Comment by lidel** [comment]
I'd vote yes: we should test DNS _protocol_ and be instance-agnostic as much as possible (ICANN DNS servers and names are sensible default for portability of test suite, but there is no need for including anything else).

It  should be up to the app depending on dnslink library to decide which DNS server is used for resolution.
For example, go-ipfs has  https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#dns  where DNS resolver provided by OS is used as default, implicit DoH is used for .eth, but user is able to override that behavior via config.

**Comment by martinheidegger** [comment]
Removed it for now in 333504c
