### ISSUE TITLE
Remove built-in doh endpoints

### ISSUE THREAD

**Issue by lidel** [dnslink-std/js#8]
Lib allows passing 'pet names' for DoH endpoints from https://github.com/martinheidegger/doh-query/blob/main/endpoints.md

## Concern 

Maintenance costs, eventual rot of the list.

## Ask

- Remove DoH list from the lib.
- Require full URL of DoH endpoint to be explicitly provided

**Comment by martinheidegger** [comment]
The latest version of dnslink has no names of well-known entries anymore.
